version: '3.0'
services:

  chatbot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    container_name: rasa
    networks:
      - rasa-network
    ports:
      - 5005:8080
    volumes:
      - ./:/app
    public: true
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - --debug
      - -p 8080

  action-server:
    build:
      context: .
      dockerfile: server.Dockerfile
    image: rasa-action-server
    container_name: actions
    networks:
      - rasa-network
    ports:
      - "5055:5055"
    volumes:
      - "./actions:/app/actions"

  mongodb:
    image: mongo
    container_name: db
    networks:
      - rasa-network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: sprint4

  web:
    build:
      context: ./
      dockerfile: Web.dockerfile
    image: webchat
    container_name: webchat-app
    depends_on:
      - "chatbot"
    networks:
      - rasa-network
    ports:
      - 8080:8080

networks:
  rasa-network:
    driver: bridge
