version: "3.0"
services:
  container-bot:
    build:
      context: .
      dockerfile: rasaDock.Dockerfile
    ports:
      - 5005:80
    depends_on:
      - container-server-bot
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - --credentials
      - credentials.yml
      - --debug
      - "80"
  container-server-bot:
    build:
      context: .
      dockerfile: actionsRasa.Dockerfile
    image: rasa-actions:latest
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions

  mongodb:
    image: mongo
    container_name: db
    networks: 
      - rasa-network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: sprint4

  web:
    build:
      context: ./web/
      dockerfile: web.dockerfile
    image: webchat
    container_name: webchat-app
    depends_on:
      - container-bot
    networks: 
      - rasa-network
    ports: 
      - 8080:8080

networks: 
    rasa-network:
        driver: bridge