version: "3.0"
services:
  rasa:
    container_name: rasa
    image: juanweimar/bot04-bot
    ports:
      - 5005:5005
    depends_on:
      - action-server
    volumes:
      - ./:/app
    command:
      - rasa
      - run
      - --enable-api
      - --cors
      - "*"
    user: root
    public: true
    networks: 
      - all
    
  action-server:
    container_name: webactions
    image: juanweimar/bot04-bot
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions
    command:
      - rasa
      - run
      - actions


  mongodb:
    image: mongo
    container_name: db
    networks: 
      - rasa-network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test

  web:
    container_name: webchat
    image: juanweimar/bot04-web
    ports: 
      - "8080:8080"
    depends_on:
      - action-server
      - rasa

networks: 
    rasa-network:
        driver: bridge